/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.service.serviceBuilder.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Ram service. Represents a row in the &quot;Ram&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.service.serviceBuilder.model.impl.RamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.service.serviceBuilder.model.impl.RamImpl}.
 * </p>
 *
 * @author NgocBao
 * @see Ram
 * @see com.service.serviceBuilder.model.impl.RamImpl
 * @see com.service.serviceBuilder.model.impl.RamModelImpl
 * @generated
 */
public interface RamModel extends BaseModel<Ram> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ram model instance should use the {@link Ram} interface instead.
	 */

	/**
	 * Returns the primary key of this ram.
	 *
	 * @return the primary key of this ram
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ram.
	 *
	 * @param primaryKey the primary key of this ram
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ram ID of this ram.
	 *
	 * @return the ram ID of this ram
	 */
	public long getRamId();

	/**
	 * Sets the ram ID of this ram.
	 *
	 * @param ramId the ram ID of this ram
	 */
	public void setRamId(long ramId);

	/**
	 * Returns the time of this ram.
	 *
	 * @return the time of this ram
	 */
	public Date getTime();

	/**
	 * Sets the time of this ram.
	 *
	 * @param time the time of this ram
	 */
	public void setTime(Date time);

	/**
	 * Returns the min of this ram.
	 *
	 * @return the min of this ram
	 */
	public double getMin();

	/**
	 * Sets the min of this ram.
	 *
	 * @param min the min of this ram
	 */
	public void setMin(double min);

	/**
	 * Returns the max of this ram.
	 *
	 * @return the max of this ram
	 */
	public double getMax();

	/**
	 * Sets the max of this ram.
	 *
	 * @param max the max of this ram
	 */
	public void setMax(double max);

	/**
	 * Returns the aver of this ram.
	 *
	 * @return the aver of this ram
	 */
	public double getAver();

	/**
	 * Sets the aver of this ram.
	 *
	 * @param aver the aver of this ram
	 */
	public void setAver(double aver);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.service.serviceBuilder.model.Ram ram);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.service.serviceBuilder.model.Ram> toCacheModel();

	@Override
	public com.service.serviceBuilder.model.Ram toEscapedModel();

	@Override
	public com.service.serviceBuilder.model.Ram toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}