/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.entity.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.nlu.entity.model.Alarm;
import com.nlu.entity.service.AlarmLocalServiceUtil;

/**
 * The extended model base implementation for the Alarm service. Represents a row in the &quot;Alarm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AlarmImpl}.
 * </p>
 *
 * @author NgocBao
 * @see AlarmImpl
 * @see com.nlu.entity.model.Alarm
 * @generated
 */
public abstract class AlarmBaseImpl extends AlarmModelImpl implements Alarm {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a alarm model instance should use the {@link Alarm} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			AlarmLocalServiceUtil.addAlarm(this);
		}
		else {
			AlarmLocalServiceUtil.updateAlarm(this);
		}
	}
}