/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.entity.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.nlu.entity.model.AlarmInfo;
import com.nlu.entity.model.AlarmInfoModel;
import com.nlu.entity.model.AlarmInfoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AlarmInfo service. Represents a row in the &quot;AlarmInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.nlu.entity.model.AlarmInfoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AlarmInfoImpl}.
 * </p>
 *
 * @author NgocBao
 * @see AlarmInfoImpl
 * @see com.nlu.entity.model.AlarmInfo
 * @see com.nlu.entity.model.AlarmInfoModel
 * @generated
 */
@JSON(strict = true)
public class AlarmInfoModelImpl extends BaseModelImpl<AlarmInfo>
	implements AlarmInfoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a alarm info model instance should use the {@link com.nlu.entity.model.AlarmInfo} interface instead.
	 */
	public static final String TABLE_NAME = "AlarmInfo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "alarmInfoId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "mail", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table AlarmInfo (alarmInfoId LONG not null primary key,name VARCHAR(75) null,mail VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table AlarmInfo";
	public static final String ORDER_BY_JPQL = " ORDER BY alarmInfo.alarmInfoId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AlarmInfo.alarmInfoId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.nlu.entity.model.AlarmInfo"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.nlu.entity.model.AlarmInfo"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.nlu.entity.model.AlarmInfo"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;
	public static long ALARMINFOID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AlarmInfo toModel(AlarmInfoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AlarmInfo model = new AlarmInfoImpl();

		model.setAlarmInfoId(soapModel.getAlarmInfoId());
		model.setName(soapModel.getName());
		model.setMail(soapModel.getMail());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AlarmInfo> toModels(AlarmInfoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AlarmInfo> models = new ArrayList<AlarmInfo>(soapModels.length);

		for (AlarmInfoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.nlu.entity.model.AlarmInfo"));

	public AlarmInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _alarmInfoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAlarmInfoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _alarmInfoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AlarmInfo.class;
	}

	@Override
	public String getModelClassName() {
		return AlarmInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("alarmInfoId", getAlarmInfoId());
		attributes.put("name", getName());
		attributes.put("mail", getMail());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long alarmInfoId = (Long)attributes.get("alarmInfoId");

		if (alarmInfoId != null) {
			setAlarmInfoId(alarmInfoId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String mail = (String)attributes.get("mail");

		if (mail != null) {
			setMail(mail);
		}
	}

	@JSON
	@Override
	public long getAlarmInfoId() {
		return _alarmInfoId;
	}

	@Override
	public void setAlarmInfoId(long alarmInfoId) {
		_alarmInfoId = alarmInfoId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getMail() {
		if (_mail == null) {
			return StringPool.BLANK;
		}
		else {
			return _mail;
		}
	}

	@Override
	public void setMail(String mail) {
		_mail = mail;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AlarmInfo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AlarmInfo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AlarmInfo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AlarmInfoImpl alarmInfoImpl = new AlarmInfoImpl();

		alarmInfoImpl.setAlarmInfoId(getAlarmInfoId());
		alarmInfoImpl.setName(getName());
		alarmInfoImpl.setMail(getMail());

		alarmInfoImpl.resetOriginalValues();

		return alarmInfoImpl;
	}

	@Override
	public int compareTo(AlarmInfo alarmInfo) {
		long primaryKey = alarmInfo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AlarmInfo)) {
			return false;
		}

		AlarmInfo alarmInfo = (AlarmInfo)obj;

		long primaryKey = alarmInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		AlarmInfoModelImpl alarmInfoModelImpl = this;

		alarmInfoModelImpl._originalName = alarmInfoModelImpl._name;

		alarmInfoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AlarmInfo> toCacheModel() {
		AlarmInfoCacheModel alarmInfoCacheModel = new AlarmInfoCacheModel();

		alarmInfoCacheModel.alarmInfoId = getAlarmInfoId();

		alarmInfoCacheModel.name = getName();

		String name = alarmInfoCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			alarmInfoCacheModel.name = null;
		}

		alarmInfoCacheModel.mail = getMail();

		String mail = alarmInfoCacheModel.mail;

		if ((mail != null) && (mail.length() == 0)) {
			alarmInfoCacheModel.mail = null;
		}

		return alarmInfoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{alarmInfoId=");
		sb.append(getAlarmInfoId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", mail=");
		sb.append(getMail());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.nlu.entity.model.AlarmInfo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>alarmInfoId</column-name><column-value><![CDATA[");
		sb.append(getAlarmInfoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mail</column-name><column-value><![CDATA[");
		sb.append(getMail());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AlarmInfo.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			AlarmInfo.class
		};
	private long _alarmInfoId;
	private String _name;
	private String _originalName;
	private String _mail;
	private long _columnBitmask;
	private AlarmInfo _escapedModel;
}