/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.entity.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Heap service. Represents a row in the &quot;Heap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nlu.entity.model.impl.HeapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nlu.entity.model.impl.HeapImpl}.
 * </p>
 *
 * @author NgocBao
 * @see Heap
 * @see com.nlu.entity.model.impl.HeapImpl
 * @see com.nlu.entity.model.impl.HeapModelImpl
 * @generated
 */
public interface HeapModel extends BaseModel<Heap> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a heap model instance should use the {@link Heap} interface instead.
	 */

	/**
	 * Returns the primary key of this heap.
	 *
	 * @return the primary key of this heap
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this heap.
	 *
	 * @param primaryKey the primary key of this heap
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the heap ID of this heap.
	 *
	 * @return the heap ID of this heap
	 */
	public long getHeapId();

	/**
	 * Sets the heap ID of this heap.
	 *
	 * @param heapId the heap ID of this heap
	 */
	public void setHeapId(long heapId);

	/**
	 * Returns the time of this heap.
	 *
	 * @return the time of this heap
	 */
	public Date getTime();

	/**
	 * Sets the time of this heap.
	 *
	 * @param time the time of this heap
	 */
	public void setTime(Date time);

	/**
	 * Returns the value of this heap.
	 *
	 * @return the value of this heap
	 */
	public double getValue();

	/**
	 * Sets the value of this heap.
	 *
	 * @param value the value of this heap
	 */
	public void setValue(double value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.nlu.entity.model.Heap heap);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.nlu.entity.model.Heap> toCacheModel();

	@Override
	public com.nlu.entity.model.Heap toEscapedModel();

	@Override
	public com.nlu.entity.model.Heap toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}