/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.entity.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Network service. Represents a row in the &quot;Network&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nlu.entity.model.impl.NetworkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nlu.entity.model.impl.NetworkImpl}.
 * </p>
 *
 * @author NgocBao
 * @see Network
 * @see com.nlu.entity.model.impl.NetworkImpl
 * @see com.nlu.entity.model.impl.NetworkModelImpl
 * @generated
 */
public interface NetworkModel extends BaseModel<Network> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a network model instance should use the {@link Network} interface instead.
	 */

	/**
	 * Returns the primary key of this network.
	 *
	 * @return the primary key of this network
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this network.
	 *
	 * @param primaryKey the primary key of this network
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the network ID of this network.
	 *
	 * @return the network ID of this network
	 */
	public long getNetworkId();

	/**
	 * Sets the network ID of this network.
	 *
	 * @param networkId the network ID of this network
	 */
	public void setNetworkId(long networkId);

	/**
	 * Returns the time of this network.
	 *
	 * @return the time of this network
	 */
	public Date getTime();

	/**
	 * Sets the time of this network.
	 *
	 * @param time the time of this network
	 */
	public void setTime(Date time);

	/**
	 * Returns the down of this network.
	 *
	 * @return the down of this network
	 */
	public double getDown();

	/**
	 * Sets the down of this network.
	 *
	 * @param down the down of this network
	 */
	public void setDown(double down);

	/**
	 * Returns the up of this network.
	 *
	 * @return the up of this network
	 */
	public double getUp();

	/**
	 * Sets the up of this network.
	 *
	 * @param up the up of this network
	 */
	public void setUp(double up);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.nlu.entity.model.Network network);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.nlu.entity.model.Network> toCacheModel();

	@Override
	public com.nlu.entity.model.Network toEscapedModel();

	@Override
	public com.nlu.entity.model.Network toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}