/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.entity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SessionRequest service. Represents a row in the &quot;SessionRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nlu.entity.model.impl.SessionRequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nlu.entity.model.impl.SessionRequestImpl}.
 * </p>
 *
 * @author NgocBao
 * @see SessionRequest
 * @see com.nlu.entity.model.impl.SessionRequestImpl
 * @see com.nlu.entity.model.impl.SessionRequestModelImpl
 * @generated
 */
public interface SessionRequestModel extends BaseModel<SessionRequest> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a session request model instance should use the {@link SessionRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this session request.
	 *
	 * @return the primary key of this session request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this session request.
	 *
	 * @param primaryKey the primary key of this session request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the session request ID of this session request.
	 *
	 * @return the session request ID of this session request
	 */
	public long getSessionRequestId();

	/**
	 * Sets the session request ID of this session request.
	 *
	 * @param sessionRequestId the session request ID of this session request
	 */
	public void setSessionRequestId(long sessionRequestId);

	/**
	 * Returns the session ID of this session request.
	 *
	 * @return the session ID of this session request
	 */
	@AutoEscape
	public String getSessionId();

	/**
	 * Sets the session ID of this session request.
	 *
	 * @param sessionId the session ID of this session request
	 */
	public void setSessionId(String sessionId);

	/**
	 * Returns the time of this session request.
	 *
	 * @return the time of this session request
	 */
	public Date getTime();

	/**
	 * Sets the time of this session request.
	 *
	 * @param time the time of this session request
	 */
	public void setTime(Date time);

	/**
	 * Returns the ip of this session request.
	 *
	 * @return the ip of this session request
	 */
	@AutoEscape
	public String getIp();

	/**
	 * Sets the ip of this session request.
	 *
	 * @param ip the ip of this session request
	 */
	public void setIp(String ip);

	/**
	 * Returns the browser of this session request.
	 *
	 * @return the browser of this session request
	 */
	@AutoEscape
	public String getBrowser();

	/**
	 * Sets the browser of this session request.
	 *
	 * @param browser the browser of this session request
	 */
	public void setBrowser(String browser);

	/**
	 * Returns the os of this session request.
	 *
	 * @return the os of this session request
	 */
	@AutoEscape
	public String getOs();

	/**
	 * Sets the os of this session request.
	 *
	 * @param os the os of this session request
	 */
	public void setOs(String os);

	/**
	 * Returns the login of this session request.
	 *
	 * @return the login of this session request
	 */
	public boolean getLogin();

	/**
	 * Returns <code>true</code> if this session request is login.
	 *
	 * @return <code>true</code> if this session request is login; <code>false</code> otherwise
	 */
	public boolean isLogin();

	/**
	 * Sets whether this session request is login.
	 *
	 * @param login the login of this session request
	 */
	public void setLogin(boolean login);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.nlu.entity.model.SessionRequest sessionRequest);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.nlu.entity.model.SessionRequest> toCacheModel();

	@Override
	public com.nlu.entity.model.SessionRequest toEscapedModel();

	@Override
	public com.nlu.entity.model.SessionRequest toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}