/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.entity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the diachi service. Represents a row in the &quot;diachi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nlu.entity.model.impl.diachiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nlu.entity.model.impl.diachiImpl}.
 * </p>
 *
 * @author NgocBao
 * @see diachi
 * @see com.nlu.entity.model.impl.diachiImpl
 * @see com.nlu.entity.model.impl.diachiModelImpl
 * @generated
 */
public interface diachiModel extends BaseModel<diachi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a diachi model instance should use the {@link diachi} interface instead.
	 */

	/**
	 * Returns the primary key of this diachi.
	 *
	 * @return the primary key of this diachi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this diachi.
	 *
	 * @param primaryKey the primary key of this diachi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this diachi.
	 *
	 * @return the ID of this diachi
	 */
	public long getId();

	/**
	 * Sets the ID of this diachi.
	 *
	 * @param id the ID of this diachi
	 */
	public void setId(long id);

	/**
	 * Returns the tinh of this diachi.
	 *
	 * @return the tinh of this diachi
	 */
	@AutoEscape
	public String getTinh();

	/**
	 * Sets the tinh of this diachi.
	 *
	 * @param tinh the tinh of this diachi
	 */
	public void setTinh(String tinh);

	/**
	 * Returns the huyen of this diachi.
	 *
	 * @return the huyen of this diachi
	 */
	@AutoEscape
	public String getHuyen();

	/**
	 * Sets the huyen of this diachi.
	 *
	 * @param huyen the huyen of this diachi
	 */
	public void setHuyen(String huyen);

	/**
	 * Returns the xa of this diachi.
	 *
	 * @return the xa of this diachi
	 */
	@AutoEscape
	public String getXa();

	/**
	 * Sets the xa of this diachi.
	 *
	 * @param xa the xa of this diachi
	 */
	public void setXa(String xa);

	/**
	 * Returns the duong of this diachi.
	 *
	 * @return the duong of this diachi
	 */
	@AutoEscape
	public String getDuong();

	/**
	 * Sets the duong of this diachi.
	 *
	 * @param duong the duong of this diachi
	 */
	public void setDuong(String duong);

	/**
	 * Returns the duong khac of this diachi.
	 *
	 * @return the duong khac of this diachi
	 */
	@AutoEscape
	public String getDuongKhac();

	/**
	 * Sets the duong khac of this diachi.
	 *
	 * @param duongKhac the duong khac of this diachi
	 */
	public void setDuongKhac(String duongKhac);

	/**
	 * Returns the khu pho of this diachi.
	 *
	 * @return the khu pho of this diachi
	 */
	@AutoEscape
	public String getKhuPho();

	/**
	 * Sets the khu pho of this diachi.
	 *
	 * @param khuPho the khu pho of this diachi
	 */
	public void setKhuPho(String khuPho);

	/**
	 * Returns the so nha of this diachi.
	 *
	 * @return the so nha of this diachi
	 */
	@AutoEscape
	public String getSoNha();

	/**
	 * Sets the so nha of this diachi.
	 *
	 * @param soNha the so nha of this diachi
	 */
	public void setSoNha(String soNha);

	/**
	 * Returns the quoc gia of this diachi.
	 *
	 * @return the quoc gia of this diachi
	 */
	@AutoEscape
	public String getQuocGia();

	/**
	 * Sets the quoc gia of this diachi.
	 *
	 * @param quocGia the quoc gia of this diachi
	 */
	public void setQuocGia(String quocGia);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.nlu.entity.model.diachi diachi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.nlu.entity.model.diachi> toCacheModel();

	@Override
	public com.nlu.entity.model.diachi toEscapedModel();

	@Override
	public com.nlu.entity.model.diachi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}