/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.entity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AlarmInfo service. Represents a row in the &quot;AlarmInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nlu.entity.model.impl.AlarmInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nlu.entity.model.impl.AlarmInfoImpl}.
 * </p>
 *
 * @author NgocBao
 * @see AlarmInfo
 * @see com.nlu.entity.model.impl.AlarmInfoImpl
 * @see com.nlu.entity.model.impl.AlarmInfoModelImpl
 * @generated
 */
public interface AlarmInfoModel extends BaseModel<AlarmInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a alarm info model instance should use the {@link AlarmInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this alarm info.
	 *
	 * @return the primary key of this alarm info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this alarm info.
	 *
	 * @param primaryKey the primary key of this alarm info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the alarm info ID of this alarm info.
	 *
	 * @return the alarm info ID of this alarm info
	 */
	public long getAlarmInfoId();

	/**
	 * Sets the alarm info ID of this alarm info.
	 *
	 * @param alarmInfoId the alarm info ID of this alarm info
	 */
	public void setAlarmInfoId(long alarmInfoId);

	/**
	 * Returns the name of this alarm info.
	 *
	 * @return the name of this alarm info
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this alarm info.
	 *
	 * @param name the name of this alarm info
	 */
	public void setName(String name);

	/**
	 * Returns the mail of this alarm info.
	 *
	 * @return the mail of this alarm info
	 */
	@AutoEscape
	public String getMail();

	/**
	 * Sets the mail of this alarm info.
	 *
	 * @param mail the mail of this alarm info
	 */
	public void setMail(String mail);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.nlu.entity.model.AlarmInfo alarmInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.nlu.entity.model.AlarmInfo> toCacheModel();

	@Override
	public com.nlu.entity.model.AlarmInfo toEscapedModel();

	@Override
	public com.nlu.entity.model.AlarmInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}