/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.entity.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.nlu.entity.model.diachi;
import com.nlu.entity.service.diachiLocalServiceUtil;

/**
 * The extended model base implementation for the diachi service. Represents a row in the &quot;diachi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link diachiImpl}.
 * </p>
 *
 * @author NgocBao
 * @see diachiImpl
 * @see com.nlu.entity.model.diachi
 * @generated
 */
public abstract class diachiBaseImpl extends diachiModelImpl implements diachi {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a diachi model instance should use the {@link diachi} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			diachiLocalServiceUtil.adddiachi(this);
		}
		else {
			diachiLocalServiceUtil.updatediachi(this);
		}
	}
}