/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nlu.entity.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.nlu.entity.model.Network;
import com.nlu.entity.model.NetworkModel;
import com.nlu.entity.model.NetworkSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Network service. Represents a row in the &quot;Network&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.nlu.entity.model.NetworkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NetworkImpl}.
 * </p>
 *
 * @author NgocBao
 * @see NetworkImpl
 * @see com.nlu.entity.model.Network
 * @see com.nlu.entity.model.NetworkModel
 * @generated
 */
@JSON(strict = true)
public class NetworkModelImpl extends BaseModelImpl<Network>
	implements NetworkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a network model instance should use the {@link com.nlu.entity.model.Network} interface instead.
	 */
	public static final String TABLE_NAME = "Network";
	public static final Object[][] TABLE_COLUMNS = {
			{ "networkId", Types.BIGINT },
			{ "time_", Types.TIMESTAMP },
			{ "down", Types.DOUBLE },
			{ "up", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table Network (networkId LONG not null primary key,time_ DATE null,down DOUBLE,up DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table Network";
	public static final String ORDER_BY_JPQL = " ORDER BY network.networkId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Network.networkId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.nlu.entity.model.Network"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.nlu.entity.model.Network"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Network toModel(NetworkSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Network model = new NetworkImpl();

		model.setNetworkId(soapModel.getNetworkId());
		model.setTime(soapModel.getTime());
		model.setDown(soapModel.getDown());
		model.setUp(soapModel.getUp());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Network> toModels(NetworkSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Network> models = new ArrayList<Network>(soapModels.length);

		for (NetworkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.nlu.entity.model.Network"));

	public NetworkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _networkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNetworkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _networkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Network.class;
	}

	@Override
	public String getModelClassName() {
		return Network.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("networkId", getNetworkId());
		attributes.put("time", getTime());
		attributes.put("down", getDown());
		attributes.put("up", getUp());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long networkId = (Long)attributes.get("networkId");

		if (networkId != null) {
			setNetworkId(networkId);
		}

		Date time = (Date)attributes.get("time");

		if (time != null) {
			setTime(time);
		}

		Double down = (Double)attributes.get("down");

		if (down != null) {
			setDown(down);
		}

		Double up = (Double)attributes.get("up");

		if (up != null) {
			setUp(up);
		}
	}

	@JSON
	@Override
	public long getNetworkId() {
		return _networkId;
	}

	@Override
	public void setNetworkId(long networkId) {
		_networkId = networkId;
	}

	@JSON
	@Override
	public Date getTime() {
		return _time;
	}

	@Override
	public void setTime(Date time) {
		_time = time;
	}

	@JSON
	@Override
	public double getDown() {
		return _down;
	}

	@Override
	public void setDown(double down) {
		_down = down;
	}

	@JSON
	@Override
	public double getUp() {
		return _up;
	}

	@Override
	public void setUp(double up) {
		_up = up;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Network.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Network toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Network)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NetworkImpl networkImpl = new NetworkImpl();

		networkImpl.setNetworkId(getNetworkId());
		networkImpl.setTime(getTime());
		networkImpl.setDown(getDown());
		networkImpl.setUp(getUp());

		networkImpl.resetOriginalValues();

		return networkImpl;
	}

	@Override
	public int compareTo(Network network) {
		int value = 0;

		if (getNetworkId() < network.getNetworkId()) {
			value = -1;
		}
		else if (getNetworkId() > network.getNetworkId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Network)) {
			return false;
		}

		Network network = (Network)obj;

		long primaryKey = network.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Network> toCacheModel() {
		NetworkCacheModel networkCacheModel = new NetworkCacheModel();

		networkCacheModel.networkId = getNetworkId();

		Date time = getTime();

		if (time != null) {
			networkCacheModel.time = time.getTime();
		}
		else {
			networkCacheModel.time = Long.MIN_VALUE;
		}

		networkCacheModel.down = getDown();

		networkCacheModel.up = getUp();

		return networkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{networkId=");
		sb.append(getNetworkId());
		sb.append(", time=");
		sb.append(getTime());
		sb.append(", down=");
		sb.append(getDown());
		sb.append(", up=");
		sb.append(getUp());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.nlu.entity.model.Network");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>networkId</column-name><column-value><![CDATA[");
		sb.append(getNetworkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>time</column-name><column-value><![CDATA[");
		sb.append(getTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>down</column-name><column-value><![CDATA[");
		sb.append(getDown());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>up</column-name><column-value><![CDATA[");
		sb.append(getUp());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Network.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Network.class
		};
	private long _networkId;
	private Date _time;
	private double _down;
	private double _up;
	private Network _escapedModel;
}